# Generated by Django 3.2.7 on 2021-09-14 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dog',
            table='dogs',
        ),
    ]
