# Generated by Django 3.2.7 on 2021-09-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_alter_dog_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='owner',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
