# Generated by Django 3.2.7 on 2021-09-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_auto_20210914_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
